config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations'
  }
  root 'home#index'

  resources :posts do
    resource :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: { message: 'Please fill in the comment content!' }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  validates :email, uniqueness: true

  # :nocov:
  def self.new_with_session(params, session)
    super.tap do |user|
      if session['devise.facebook_data'].present? && session['devise.facebook_data']['extra']['raw_info'].present?
        user.email = session['devise.facebook_data']['extra']['raw_info']['email'] if user.email.blank?
      end
    end
  end
  # :nocov:

  # :nocov:
  def self.from_omniauth(auth)
    user = find_by(email: auth.info.email)
    if user.present?
      user.update(provider: auth.provider, uid: auth.uid) if user.provider.blank? && user.uid.blank?
    else
      user = create do |u|
        u.provider = auth.provider
        u.uid = auth.uid
        u.email = auth.info.email
        u.password = Devise.friendly_token[0, 20]
      end
    end
    user
  end
  # :nocov:
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'The comment is created!'
      redirect_to @post
    else
      render template: 'posts/show'
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :find_post, only: %i[show destroy update edit]

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    if @post.save
      flash[:notice] = 'The post has been created'
      redirect_to @post
    else
      render :new
    end
  end

  def show
    authorize @post
    @comment = @post.comments.build
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      flash[:notice] = 'The post has been updated'
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    authorize @post
    @post.destroy
    flash[:notice] = 'The post has been deleted!'
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def facebook
    generic_callback('facebook')
  end

  def generic_callback(provider)
    @identity = User.from_omniauth(request.env['omniauth.auth'])

    @user = @identity || current_user
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{facebook}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_authentication_links(class_name = nil)
    if user_signed_in?
      link_to 'Log out', destroy_user_session_path, method: :delete, class: class_name
    else
      link_to('Log in', new_user_session_path, class: class_name) +
          link_to('Register', new_user_registration_path, class: class_name)
    end
  end

  def render_new_post_link(class_name = nil)
    link_to('New post', new_post_path, class: class_name) if user_signed_in?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.slim
.card.my-4
  h5.card-header Leave a comment:
  .card-body
    = form_with model: @comment, url: [@post, @comment], local: true do |f|
      .form-group
        = f.text_area :content, placeholder: 'Content', class: 'form-control'
      .form-group
        = f.submit class: 'btn btn-primary'

app/views/home/index.html.slim
.container.px-5
  = render 'layouts/messages'
  .row
    .col-md-8
      - if @posts.present?
        h1.text-info.my-4 Post list

        - @posts.reverse.each do |p|
          .card.mb-4
            img.card-img-top src="http://placehold.it/750x300"
            .card-body
              h2.card-title = p.title
              p.card-text.text-truncate = p.body
              = link_to "Read More",post_path(p), class: 'btn btn-primary'
            .card-footer.text-muted
              | Posted by #{p.user.email} on #{p.created_at.localtime}
      - else
        h2.text-center.my-auto.text-warning.py-5 There are not any posts yet

    .col-md-4
      h2 this is the sidebar

= render 'layouts/footer'

app/views/layouts/_footer.html.slim
footer.py-2.bg-dark
  p.text-white.text-center
    | This is my foot

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  - if key == 'notice'
    div [class="alert alert-success fade show text-center"]
      strong = value
      button [type='button' data-dismiss='alert' class='close' aria-label="close" ]
        span [aria-hidden="true" ] &times;
  - elsif key == 'alert'
    div [class="alert alert-danger fade show text-center"]
      strong = value
      button [type='button' data-dismiss='alert' class='close' aria-label="close" ]
        span [aria-hidden="true" ] &times;

app/views/layouts/_navbar.html.slim
nav [class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"]
  .container.p-0
    = link_to "OWEN", root_path, class: "navbar-brand"

    button [class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"]
      span [class="navbar-toggler-icon"]

    div [class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup"]
      ul [class="navbar-nav"]

        li [class="nav-item"]
          = link_to "Home", root_path, class: "nav-link"
          span [class="sr-only"] (current)

        li [class="nav-item"]
          = render_new_post_link("nav-link")

        li [class="nav-item dropdown"]
          = link_to "Account", "#", class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }

          .dropdown-menu [aria-labelledby="navbarDropdownMenuLink"]
            = render_authentication_links("dropdown-item")

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BlogAssignment
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width,initial-scale=1"
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  / script src="https://kit.fontawesome.com/1b32ad5942.js" crossorigin="anonymous"
  body class="#{controller_name}-#{action_name}-view"
    = render 'layouts/navbar'
    = yield

app/views/posts/_form.html.slim
= form_with model: @post, local: true do |f|
  - if @post.errors.any?
    - @post.errors.full_messages.each do |msg|
      .alert.alert-danger.alert-dismissible.fade.show role="alert"
        = msg
        button [class='close' aria-label="Close" type='button' data-dismiss="alert" ]
          span [aria-hidden="true" ] &times;

  .form-group
    = f.text_field :title, placeholder: 'Post title', class: 'form-control'
  .form-group
    = f.text_area :body, placeholder: 'Post content', class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-primary btn-block'

app/views/posts/edit.html.slim
.container
  h3.text-center You are editing the post
  = render 'posts/form'

app/views/posts/new.html.slim
.container
  h3.text-center You are creating a new post
  = render 'posts/form'

app/views/posts/show.html.slim
.container.pb-3
  - if @comment.errors.any?
    - @comment.errors.each do |_field, msg|
      .alert.alert-danger.alert-dismissible.fade.show role="alert"
        = msg
        button [class='close' aria-label="Close" type='button' data-dismiss="alert" ]
          span [aria-hidden="true" ] &times;
  / = @comment.errors.messages.inspect
  .row.text-wrap
    / Post content column
    .col-md-8
      h1.my-4 = @post.title
      p.lead
        | By
        =< @post.user.email
      hr
      p
        | Posted on
        =< @post.created_at.localtime.asctime
      hr

        = simple_format @post.body, class: 'text-justify text-break'
      hr
      / Comment input
      = render 'comments/form'
      / show comments
      - if @post.comments.exists?
        - @post.comments.select(&:persisted?).reverse.each do |c|
          .media.mb-4
            img.mr-3.rounded-circle src='http://placehold.it/50x50' alt=''
            .media-body.text-justify.text-break
              h5.mt-0 = c.user.email
              p.text-muted
                | On #{c.created_at.localtime}
              = c.content

    / Sidebar column
    .col-md-4
      .card.my-4
        h5.card-header Search
        .card-body
          .input-group
            input.form-control type='text'placeholder='Search for...'
            span.input-group-btn
              button.btn.btn-primary GO
      .card.my-4
        h5.card-header Categories
        .card-body
          .row
            .col-lg-6
              ul.list-unstyled.mb-0
                li.text-center = link_to "Lorem", '#'
                li.text-center = link_to "Lorem", '#'
                li.text-center = link_to "Lorem", '#'
            .col-lg-6
              ul.list-unstyled.mb-0
                li.text-center = link_to "Lorem", '#'
                li.text-center = link_to "Lorem", '#'
                li.text-center = link_to "Lorem", '#'
      .card.my-4
        h5.card-header Post Widgets
        .card-body
          .row
            .col-lg-6
              = link_to 'Like', '#', class: 'btn btn-primary mb-1'
              =< link_to 'Share', '#', class: 'btn btn-primary mb-1'
              = link_to 'Star', '#', class: 'btn btn-primary mb-1'
            .col-lg-6
              = link_to 'Edit this post',edit_post_path(@post), class: 'btn btn-primary mb-1 btn-block' if policy(@post).edit?
              = link_to 'Delete this post', post_path(@post), class: 'btn btn-danger mb-1 btn-block', method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } if policy(@post).destroy?

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  - resource.errors.full_messages.each do |message|
    .alert.alert-danger.alert-dismissible.fade.show role='alert'
      strong = message
      button type='button' class='close' data-dismiss='alert' aria-label='Close'
        span [aria-hidden='true']  &times;

/ - if resource.errors.any?
/   #error_explanation.alert.alert-danger.alert-dismissible.fade.show role='alert'
/     h2.alert-heading
/       = I18n.t("errors.messages.not_saved",
/               count: resource.errors.count,
/               resource: resource.class.model_name.human.downcase)
/     ul
/       - resource.errors.full_messages.each do |message|
/         li
/           = message
/     button type='button' class='close' data-dismiss='alert' aria-label='Close'
/       span [aria-hidden='true']  &times;

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name), class: 'btn btn-secondary mr-1', type: 'button'
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-secondary mr-1', type: 'button'
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name), class: 'btn btn-secondary mr-1', type: 'button'
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'btn btn-secondary mr-1', type: 'button'
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'btn btn-secondary mr-1', type: 'button'
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'btn btn-secondary mr-1', type: 'button'
    br